### ISSUE TITLE
VS attempts to compile a non-existent file

### ISSUE THREAD

**Issue by InfinityGhost** [mrflashstudio/OsuParsers#1]
When attempting to build the parser, it tries to include Program.cs which doesn't exist.

> CSC : error CS2001: Source file 'D:\docs\Extra Repos\OsuBeatmapParser\OsuBeatmapParser\Program.cs' could not be found.

**Comment by mrflashstudio** [comment]
Hello, thanks for your report! This seems to be fixed. Can you reproduce this error on the latest master branch?

**Comment by InfinityGhost** [comment]
Issue solved, no issues with it since.
