### ISSUE TITLE
I am dump...

### ISSUE THREAD

**Issue by iiZLucas** [mrflashstudio/OsuParsers#2]
I dont know how to check if the hitobject is a slider or spinner or circle. And if its a circle then how to get the curvepoint and  so on?

**Comment by mrflashstudio** [comment]
```
//parsing beatmap
Beatmap beatmap = new Parser().ParseBeatmap(@".osuPath");
//getting first hitobject
HitObject h = beatmap.HitObjects[0];
//checking its type
if (h is StandardHitCircle) //osu!standard HitCircle
{
    StandardHitCircle circle = h as StandardHitCircle;

    //let's say we want to get position of this circle
    Point position = circle.Position;
}
else if (h is StandardSlider) //osu!standard Slider
{
    StandardSlider slider = h as StandardSlider;

    //getting first curve point
    Point firstCurvePoint = slider.SliderPoints[0];
}
else if (h is StandardSpinner) //osu!standard Spinner
{
    StandardSpinner spinner = h as StandardSpinner;

    //now we want to get the endtime
    int endTime = spinner.EndTime;
}
```

I will make better documentation in the future, so hold on there!
If you have any questions left, you can ask them here, if not, then I will close this issue.

**Comment by iiZLucas** [comment]
THX dude, I didn't know about the is command :D

**Comment by piggeywig2000** [comment]
Sorry to revive this issue, just wanted to say thank you for this, because I too found it really useful.

Maybe consider adding it to the documentation - I'm inexperienced with C# and Object-Oriented programming in general, and I can imagine this tripping other people up as well.

Anyway, thanks for making this project, it's really great :)

**Comment by mrflashstudio** [comment]
Sure, I'll add it to the documentation or to the ``Usage`` section of the readme in the future. It would be nice to make the library more understandable for beginners.
