### ISSUE TITLE
Issue regarding the `TimingPoint.Inherited` variable

### ISSUE THREAD

**Issue by abstrakt8** [mrflashstudio/OsuParsers#30]
According to the [official documents of the .osu file format](https://osu.ppy.sh/help/wiki/osu!_File_Formats/Osu_(file_format)), the second to last value of each timing point line indicates if it is **uninherited** or not, however, the `TimingPoint` class uses a variable named `Inherited` for this value.

While parsing the timing point, we could store the negation of the read value into our `Inherited` variable, but we could also change the class member variable to `Uninherited` without having to negate anything.

**Comment by mrflashstudio** [comment]
`Inherited` sounds way more intuitive imo.

**Comment by abstrakt8** [comment]
Do not disagree, but if you store the exact opposite value then it's still wrong.

https://github.com/mrflashstudio/OsuParsers/blob/22484234d56ab347994ae2ecc7b03be1b32445a6/OsuParsers/Decoders/BeatmapDecoder.cs#L318-L319

Change this to the following at least: 
```
inherited = !ParseHelper.ToBool(tokens[6]); 
```

**Comment by mrflashstudio** [comment]
I thought it was already negated. Thanks for pointing this out.
