### ISSUE TITLE
[Documentation] Beatmap.GeneralSection.Length is the length of the beatmap in seconds, unlike the milliseconds stated in the docs.

### ISSUE THREAD

**Issue by palapapa** [mrflashstudio/OsuParsers#33]
[https://github.com/mrflashstudio/OsuParsers/blob/master/docs/BeatmapDocumentation.md#general-section-properties]()
Here it says 

Length | int | Beatmap length in ms.
-- | -- | --

which is wrong

**Comment by mrflashstudio** [comment]
No idea why i did that honestly
