### ISSUE TITLE
Add ability to flip Beatmap/Apply HR

### ISSUE THREAD

**Issue by MaxKruse** [mrflashstudio/OsuParsers#34]
Hello, for my project i am planning on checking replays with their intended map. For this, some replays use HR, and if a replay has HR, i would love to be able to simply flip the beatmap, e.g.

```
var beatmap = BeatmapDecoder.Decode(@"Map.osu");
var replay= ReplaypDecoder.Decode(@"Replay.osr");

if (replay.Mods == Mods::HardRock) 
{
    beatmap.Flip();
}

```

where flip would take each y-Position and equal it to

```
foreach(var object in HitObjects)
{
    var offset = object.Position.Y - 192;
    object.Position.Y -= offset;
}
```

I believe this *should* be the solution, dont have time to test it right now though.

**Comment by mrflashstudio** [comment]
Is there any reason why you can't just include it into your project?

You can implement it like this:
```csharp
foreach (var hitObject in HitObjects)
    hitObject.Position = new Vector2(hitObject.Position.X, 384f - hitObject.Position.Y);
```

**Comment by MaxKruse** [comment]
True, i assumed this project could include other functionality of beatmap manipulation, but didnt realize its actually just for the parsers and structures :P
